# Site settings
title:          Jiyun's tech blog
description:    "진짜 개발!?"
baseurl:        "/"
url:            "https://jiyun-wang7.github.io/"

# Google Analytics
google_analytics: UA-259178828-1

# Author
author:
  name:         Jiyun Wang
  url:          https://jiyun-wang7.github.io/
  email:        jiyoon3000@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale